networks:
  kcss-network:
    name: kcss-network
    external: true

x-network-restart: &network-restart
  networks:
    - kcss-network
  restart: unless-stopped

services:
  kc-checkin-bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: python kc-checkin-bot.py
    volumes:
      - .:/app
    restart: unless-stopped
